FROM python:3.12.3-slim-bookworm

ENV POETRY_VERSION=1.8.0
ENV BACKEND_PORT=7001
ENV PYTHONUNBUFFERED=1

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /app

COPY poetry.lock pyproject.toml /app/

RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

RUN playwright install --with-deps chromium

COPY ./ /app/

EXPOSE 7001

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7001"]

# ENV POETRY_VERSION 1.8.0

# # Install system dependencies
# RUN pip install "poetry==$POETRY_VERSION"

# # Set work directory
# WORKDIR /app

# # Copy only requirements to cache them in docker layer
# COPY poetry.lock pyproject.toml /app/

# # Disable the creation of virtual environments
# RUN poetry config virtualenvs.create false

# # Install dependencies
# RUN poetry install

# # Install Chromium and Linux libraries needed by Playwright screenshot previews.
# RUN playwright install --with-deps chromium

# # Copy the current directory contents into the container at /app
# COPY ./ /app/
